### ISSUE TITLE
Issues with Exceptions

### ISSUE THREAD

**Issue by tmr232** [james91b/ida_ipython#33]
This
![image](https://cloud.githubusercontent.com/assets/1386239/19213779/4f8e495e-8d7d-11e6-90d6-2bc05343a827.png)

Happens whenever I raise an exception in the IPython shell. IDA's own shell just prints the exception to the IPython window (weird too).

I'll try and look into it. The same thing happened to me with my pure-Python implementation, so for a long while I was sure my new code is the issue, but I seem to get it with current release code as well.

**Comment by tmr232** [comment]
OK. Seems this is nothing to do with exceptions, rather with the logging module. 
Seems like the following code (from IPython) fails.

``` python
>>> import logging
>>> logging.log("bla")
```

**Comment by ibookstein** [comment]
I'm having the same issue - every statement that's supposed to generate an exception, generates this instead.
I'm running IDA IPython on top of Anaconda 4.2.0 / Python 2.7.12 / IPython 5.1.0.
Trying to upgrade IDAPython version did not help.
I tried poking around (being able to only write statements that succeed is an interesting debugging experience indeed). Here are some of my findings:
There's something rotten in the logging module's configuration:

``` python
import logging

def typename(obj):
    return str(type(obj)).split("'")[1]

for logger_name, logger in logging.root.manager.loggerDict.iteritems():
    handlers = getattr(logger, 'handlers', [])
    print "Logger '{}' ({}) has {} handlers:".format(logger_name, typename(logger), len(handlers))    
    for index, handler in enumerate(handlers):
        print '\tHandler {}: {} ({})'.format(index, typename(handler), handler.stream)

Logger 'tornado.access' (logging.Logger) has 0 handlers:
Logger 'tornado' (logging.Logger) has 1 handlers:
    Handler 0: logging.StreamHandler (<open file '<stderr>', mode 'w' at 0x0529D0D0>)
Logger 'tornado.general' (logging.Logger) has 0 handlers:
Logger 'concurrent' (logging.PlaceHolder) has 0 handlers:
Logger 'IPKernelApp' (logging.Logger) has 1 handlers:
    Handler 0: logging.StreamHandler (<open file '<stderr>', mode 'w' at 0x0529D0D0>)
Logger 'tornado.application' (logging.Logger) has 0 handlers:
Logger 'concurrent.futures' (logging.Logger) has 0 handlers:
```

There's code in `kernelbase.py` that configures the `tornado` logger above:

``` python
    def configure_tornado_logger(self):
        """ Configure the tornado logging.Logger.

            Must set up the tornado logger or else tornado will call
            basicConfig for the root logger which makes the root logger
            go to the real sys.stderr instead of the capture streams.
            This function mimics the setup of logging.basicConfig.
        """
        logger = logging.getLogger('tornado')
        handler = logging.StreamHandler()  <b># default argument for stream is sys.stderr</b>
        formatter = logging.Formatter(logging.BASIC_FORMAT)
        handler.setFormatter(formatter)
        logger.addHandler(handler)
```

I'm guessing that for some reason the `ipykernel`/`logging` initialization code is running while `sys.stderr` is pointing at the original `stderr` of the process (`fileno == -2`), which doesn't exist for GUI applications, leading to the `Bad file descriptor` error.

Also, when manually patching the streams to point to the `ipykernel.iostream.OutStream` which is actually in `sys.stderr`, I get the following error:

``` python
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\ipykernel\kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\ipykernel\kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\ipykernel\zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2846, in run_ast_nodes
    self.showtraceback()
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 1824, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 1406, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 1314, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 1164, in structured_traceback
    tb_offset)
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 1107, in format_exception_as_a_whole
    head = self.prepare_header(etype, self.long_header)
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 1041, in prepare_header
    width = min(75, get_terminal_size()[0])
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\utils\terminal.py", line 120, in get_terminal_size
    return _get_terminal_size((defaultx, defaulty))
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\backports\shutil_get_terminal_size\get_terminal_size.py", line 91, in get_terminal_size
    size = _get_terminal_size(sys.__stdout__.fileno())
AttributeError: IDAPythonStdOut instance has no attribute 'fileno'
```

This is as far as I got at the moment, hope this helps.

**Comment by tmr232** [comment]
I think we should try and disable logging entirely to see if it solves the issue.
