### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by nharrer** [james91b/ida_ipython#35]
I am getting this exception. It's on a Windows 10 64bit Machine. Anaconda 32bit is installed. I made sure that any other python installations were removed.

The funny thing is that there is no error when I import `from ipykernel.kernelapp import IPKernelApp` in the python shell or Jupyter QtConsole.

Here is the full stacktrace:
```
Traceback (most recent call last):
  File "C:\devtools\IDA 6.8\python\ipythonEmbed.py", line 19, in <module>
    from ipykernel.kernelapp import IPKernelApp
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\__init__.py", line 48, in <module>
    from .core.application import Application
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\core\application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\core\crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 124, in <module>
    from IPython.utils import path as util_path
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\utils\path.py", line 19, in <module>
    from IPython.utils.process import system
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\utils\process.py", line 15, in <module>
    from ._process_win32 import system, getoutput, arg_split, check_pid
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\IPython\utils\_process_win32.py", line 21, in <module>
    import ctypes
  File "C:\Program Files (x86)\Anaconda2\Lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: %1 is not a valid Win32 application.
A Python Error Occurred trying to start the kernel!
```

**Comment by nharrer** [comment]
Sorry. It turned out that a previous uninstalled 64bit Installation of Anaconda left files in `C:\Users\<User>\Anaconda2`. 

The `sys.path` in IDA included that directory. However, when python was started from the python shell or Jupyter it was not included in `sys.path`. I didn't find out the reason for that.

I deleted the old leftover files and now it is working.
